In [145]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
import numpy as np
from syc.utilities import time_extractor

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [146]:
file=pd.read_json('C:\\Users\\dawit\\PycharmProjects\\hydration break\\data\\106.json').sort_values(by='match_id').reset_index()
file.tail(10)

,index,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
54,48,3869253,2022-12-05,21:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 781, 'home_team_name': 'Brazil', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 31, 'name': 'Brazil'}, 'managers': [{'id': 547, 'name': 'Adenor Leonardo Bacchi', 'nickname': 'Tite', 'dob': '1961-05-25', 'country': {'id': 31, 'name': 'Brazil'}}]}","{'away_team_id': 791, 'away_team_name': 'South Korea', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 121, 'name': 'Korea (South)'}, 'managers': [{'id': 5688, 'name': 'Paulo Jorge Gomes Bento', 'nickname': 'Paulo Bento', 'dob': '1969-06-20', 'country': {'id': 183, 'name': 'Portugal'}}]}",4,1,available,available,2023-06-06T07:12:35.194539,2023-06-19T13:27:43.114201,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",4,"{'id': 33, 'name': 'Round of 16'}","{'id': 1001115, 'name': 'Stadium 974', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 76, 'name': 'Clément Turpin', 'country': {'id': 78, 'name': 'France'}}"
55,40,3869254,2022-12-06,21:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 780, 'home_team_name': 'Portugal', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 183, 'name': 'Portugal'}, 'managers': [{'id': 607, 'name': 'Fernando Manuel Fernandes da Costa Santos', 'nickname': 'Fernando Santos', 'dob': '1954-10-10', 'country': {'id': 183, 'name': 'Portugal'}}]}","{'away_team_id': 773, 'away_team_name': 'Switzerland', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 221, 'name': 'Switzerland'}, 'managers': [{'id': 2832, 'name': 'Murat Yakin', 'nickname': None, 'dob': '1974-09-15', 'country': {'id': 221, 'name': 'Switzerland'}}]}",6,1,available,available,2023-10-31T08:50:23.629502,2023-10-31T08:52:42.971689,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",4,"{'id': 33, 'name': 'Round of 16'}","{'id': 1001114, 'name': 'Lusail Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 740, 'name': 'César Arturo Ramos Palazuelos', 'country': {'id': 147, 'name': 'Mexico'}}"
56,24,3869321,2022-12-09,19:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 941, 'home_team_name': 'Netherlands', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 160, 'name': 'Netherlands'}, 'managers': [{'id': 788, 'name': 'Louis van Gaal', 'nickname': None, 'dob': '1951-08-08', 'country': {'id': 160, 'name': 'Netherlands'}}]}","{'away_team_id': 779, 'away_team_name': 'Argentina', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 11, 'name': 'Argentina'}, 'managers': [{'id': 5677, 'name': 'Lionel Sebastián Scaloni', 'nickname': None, 'dob': '1978-05-16', 'country': {'id': 11, 'name': 'Argentina'}}]}",2,2,available,available,2025-09-04T17:24:28.888436,2025-09-07T08:42:38.594465,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",5,"{'id': 11, 'name': 'Quarter-finals'}","{'id': 1001114, 'name': 'Lusail Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 180, 'name': 'Antonio Miguel Mateu Lahoz', 'country': {'id': 214, 'name': 'Spain'}}"
57,43,3869354,2022-12-10,21:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 768, 'home_team_name': 'England', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 68, 'name': 'England'}, 'managers': [{'id': 277, 'name': 'Gareth Southgate', 'nickname': None, 'dob': '1970-09-03', 'country': {'id': 68, 'name': 'England'}}]}","{'away_team_id': 771, 'away_team_name': 'France', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 78, 'name': 'France'}, 'managers': [{'id': 545, 'name': 'Didier Deschamps', 'nickname': None, 'dob': '1968-10-15', 'country': {'id': 78, 'name': 'France'}}]}",1,2,available,available,2023-03-21T07:09:52.867230,2023-04-26T22:57:33.780657,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",5,"{'id': 11, 'name': 'Quarter-finals'}","{'id': 1001113, 'name': 'Al Bayt Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 986, 'name': 'Wilton Pereira Sampaio', 'country': {'id': 31, 'name': 'Brazil'}}"
58,45,3869420,2022-12-09,17:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 785, 'home_team_name': 'Croatia', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 56, 'name': 'Croatia'}, 'managers': [{'id': 307, 'name': 'Zlatko Dalić', 'nickname': None, 'dob': '1966-10-26', 'country': {'id': 56, 'name': 'Croatia'}}]}","{'away_team_id': 781, 'away_team_name': 'Brazil', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 31, 'name': 'Brazil'}, 'managers': [{'id': 4704, 'name': 'Telê Santana da Silva', 'nickname': 'Telê Santana', 'dob': '1931-07-26', 'country': {'id': 31, 'name': 'Brazil'}}]}",1,1,available,available,2023-04-19T06:28:33.041249,2023-04-26T23:04:13.569501,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",5,"{'id': 11, 'name': 'Quarter-finals'}","{'id': 94425, 'name': 'Education City Stadium ', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 1, 'name': 'Michael Oliver', 'country': {'id': 68, 'name': 'England'}}"
59,36,3869486,2022-12-10,17:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 788, 'home_team_name': 'Morocco', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 154, 'name': 'Morocco'}, 'managers': [{'id': 1001086, 'name': 'Hoalid Regragui', 'nickname': None, 'dob': '1975-09-23', 'country': {'id': 154, 'name': 'Morocco'}}]}","{'away_team_id': 780, 'away_team_name': 'Portugal', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 183, 'name': 'Portugal'}, 'managers': [{'id': 607, 'name': 'Fernando Manuel Fernandes da Costa Santos', 'nickname': 'Fernando Santos', 'dob': '1954-10-10', 'country': {'id': 183, 'name': 'Portugal'}}]}",1,0,available,available,2024-02-06T16:35:57.395966,2024-02-06T16:39:05.200810,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",5,"{'id': 11, 'name': 'Quarter-finals'}","{'id': 1000838, 'name': 'Al Thumama Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 1094, 'name': 'Facundo Tello Figueroa', 'country': {'id': 11, 'name': 'Argentina'}}"
60,42,3869519,2022-12-13,21:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 779, 'home_team_name': 'Argentina', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 11, 'name': 'Argentina'}, 'managers': [{'id': 5677, 'name': 'Lionel Sebastián Scaloni', 'nickname': None, 'dob': '1978-05-16', 'country': {'id': 11, 'name': 'Argentina'}}]}","{'away_team_id': 785, 'away_team_name': 'Croatia', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 56, 'name': 'Croatia'}, 'managers': [{'id': 307, 'name': 'Zlatko Dalić', 'nickname': None, 'dob': '1966-10-26', 'country': {'id': 56, 'name': 'Croatia'}}]}",3,0,available,available,2023-04-19T06:53:52.197711,2023-04-26T22:32:37.808359,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",6,"{'id': 15, 'name': 'Semi-finals'}","{'id': 1001114, 'name': 'Lusail Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 269, 'name': 'Daniele Orsato', 'country': {'id': 112, 'name': 'Italy'}}"
61,44,3869552,2022-12-14,21:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 771, 'home_team_name': 'France', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 78, 'name': 'France'}, 'managers': [{'id': 545, 'name': 'Didier Deschamps', 'nickname': None, 'dob': '1968-10-15', 'country': {'id': 78, 'name': 'France'}}]}","{'away_team_id': 788, 'away_team_name': 'Morocco', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 154, 'name': 'Morocco'}, 'managers': [{'id': 1001086, 'name': 'Hoalid Regragui', 'nickname': None, 'dob': '1975-09-23', 'country': {'id': 154, 'name': 'Morocco'}}]}",2,0,available,available,2024-02-06T16:36:46.784457,2024-02-06T16:45:42.775801,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",6,"{'id': 15, 'name': 'Semi-finals'}","{'id': 1001113, 'name': 'Al Bayt Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 740, 'name': 'César Arturo Ramos Palazuelos', 'country': {'id': 147, 'name': 'Mexico'}}"
62,28,3869684,2022-12-17,17:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 785, 'home_team_name': 'Croatia', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 56, 'name': 'Croatia'}, 'managers': [{'id': 307, 'name': 'Zlatko Dalić', 'nickname': None, 'dob': '1966-10-26', 'country': {'id': 56, 'name': 'Croatia'}}]}","{'away_team_id': 788, 'away_team_name': 'Morocco', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 154, 'name': 'Morocco'}, 'managers': [{'id': 1000518, 'name': 'Walid Regragui', 'nickname': None, 'dob': '1975-09-23', 'country': {'id': 154, 'name': 'Morocco'}}]}",2,1,available,available,2024-02-13T13:43:25.154307,2024-02-13T13:44:03.865296,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",7,"{'id': 25, 'name': '3rd Place Final'}","{'id': 1000253, 'name': 'Sheikh Khalifa International Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 2521, 'name': 'Abdulrahman Ibrahim Al Jassim', 'country': {'id': 185, 'name': 'Qatar'}}"
63,27,3869685,2022-12-18,17:00:00.000,"{'competition_id': 43, 'country_name': 'International', 'competition_name': 'FIFA World Cup'}","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 779, 'home_team_name': 'Argentina', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 11, 'name': 'Argentina'}, 'managers': [{'id': 5677, 'name': 'Lionel Sebastián Scaloni', 'nickname': None, 'dob': '1978-05-16', 'country': {'id': 11, 'name': 'Argentina'}}]}","{'away_team_id': 771, 'away_team_name': 'France', 'away_team_gender': 'male', 'away_team_group': None, 'country': {'id': 78, 'name': 'France'}, 'managers': [{'id': 545, 'name': 'Didier Deschamps', 'nickname': None, 'dob': '1968-10-15', 'country': {'id': 78, 'name': 'France'}}]}",3,3,available,available,2024-12-16T10:15:11.055845,2024-12-16T10:21:13.710934,"{'data_version': '1.1.0', 'shot_fidelity_version': '2', 'xy_fidelity_version': '2'}",7,"{'id': 26, 'name': 'Final'}","{'id': 1001114, 'name': 'Lusail Stadium', 'country': {'id': 185, 'name': 'Qatar'}}","{'id': 367, 'name': 'Szymon Marciniak', 'country': {'id': 182, 'name': 'Poland'}}"

In [147]:
data=pd.read_json('C:\\Users\\dawit\\PycharmProjects\\hydration break\\data\\2022\\3857254.json')
print(data.columns)
print(data.shape)
data.head(10)

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'duration',
       'tactics', 'related_events', 'player', 'position', 'location', 'pass',
       'carry', 'under_pressure', 'ball_receipt', 'clearance', 'out', 'duel',
       'foul_committed', 'foul_won', 'shot', 'goalkeeper', 'counterpress',
       'off_camera', 'interception', 'block', 'dribble', 'ball_recovery',
       'injury_stoppage', 'substitution'],
      dtype='str')
(3680, 36)

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,shot,goalkeeper,counterpress,off_camera,interception,block,dribble,ball_recovery,injury_stoppage,substitution
0,1f1c28b2-afc0-4986-a965-7e545df6941c,1,1,2026-09-11 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 776, 'name': 'Denmark'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9de6bcb8-368e-40d7-91c2-fabb5b932caf,2,1,2026-09-11 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 776, 'name': 'Denmark'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8e0db96c-ed4c-410f-95f2-650f0de594bb,3,1,2026-09-11 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 776, 'name': 'Denmark'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6949d93f-9fca-434a-8d66-ef2dccc8dcd2,4,1,2026-09-11 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 776, 'name': 'Denmark'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9266e43f-c76a-413b-8c25-9b61c1aefe49,5,1,2026-09-11 00:00:00.361,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 776, 'name': 'Denmark'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,86eb15d6-28af-43b9-952d-c8fa4d56c6e4,6,1,2026-09-11 00:00:00.580,0,0,"{'id': 42, 'name': 'Ball Receipt*'}",2,"{'id': 776, 'name': 'Denmark'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ebf689ee-935c-43a6-a629-387a3a9db356,7,1,2026-09-11 00:00:00.580,0,0,"{'id': 43, 'name': 'Carry'}",2,"{'id': 776, 'name': 'Denmark'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,e59abeb7-b8a4-49f8-9580-93b06348e5de,8,1,2026-09-11 00:00:01.560,0,1,"{'id': 30, 'name': 'Pass'}",2,"{'id': 776, 'name': 'Denmark'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,26bfda4b-25b7-4ac3-ae73-d41a11c49a4a,9,1,2026-09-11 00:00:02.816,0,2,"{'id': 42, 'name': 'Ball Receipt*'}",2,"{'id': 776, 'name': 'Denmark'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,103aeb5d-a816-4ed7-a12c-b56a3f61084a,10,1,2026-09-11 00:00:02.816,0,2,"{'id': 43, 'name': 'Carry'}",2,"{'id': 776, 'name': 'Denmark'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [148]:
data[data['id']=='6949d93f-9fca-434a-8d66-ef2dccc8dcd2']

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,shot,goalkeeper,counterpress,off_camera,interception,block,dribble,ball_recovery,injury_stoppage,substitution
3,6949d93f-9fca-434a-8d66-ef2dccc8dcd2,4,1,2026-09-11,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 776, 'name': 'Denmark'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
data.dtypes

id                            str
index                       int64
period                      int64
timestamp          datetime64[us]
minute                      int64
second                      int64
type                       object
possession                  int64
possession_team            object
play_pattern               object
team                       object
duration                  float64
tactics                    object
related_events             object
player                     object
position                   object
location                   object
pass                       object
carry                      object
under_pressure            float64
ball_receipt               object
clearance                  object
out                       float64
duel                       object
foul_committed             object
foul_won                   object
shot                       object
goalkeeper                 object
counterpress              float64
off_camera                float64
interception               object
block                      object
dribble                    object
ball_recovery              object
injury_stoppage            object
substitution               object
dtype: object

In [150]:
for i in data.columns:
    print(i, data[i].astype(str).nunique())

id 3680
index 3680
period 2
timestamp 2534
minute 98
second 60
type 25
possession 194
possession_team 2
play_pattern 9
team 2
duration 2150
tactics 5
related_events 3400
player 31
position 21
location 2417
pass 1063
carry 890
under_pressure 1
ball_receipt 1
clearance 5
out 1
duel 9
foul_committed 3
foul_won 3
shot 24
goalkeeper 26
counterpress 1
off_camera 1
interception 4
block 1
dribble 5
ball_recovery 1
injury_stoppage 1
substitution 9

In [151]:
data['type'].head(10)

0      {'id': 35, 'name': 'Starting XI'}
1      {'id': 35, 'name': 'Starting XI'}
2       {'id': 18, 'name': 'Half Start'}
3       {'id': 18, 'name': 'Half Start'}
4             {'id': 30, 'name': 'Pass'}
5    {'id': 42, 'name': 'Ball Receipt*'}
6            {'id': 43, 'name': 'Carry'}
7             {'id': 30, 'name': 'Pass'}
8    {'id': 42, 'name': 'Ball Receipt*'}
9            {'id': 43, 'name': 'Carry'}
Name: type, dtype: object

In [152]:
data.type.to_list()
unique_list_id=[]
unique_list_name=[]
for i in data.type.to_list():
    if i['id'] not in unique_list_id:
        unique_list_id.append(i['id'])
    if i['name'] not in unique_list_name:
        unique_list_name.append(i['name'])
print(unique_list_name)
print(unique_list_id)

['Starting XI', 'Half Start', 'Pass', 'Ball Receipt*', 'Carry', 'Pressure', 'Clearance', 'Ball Recovery', 'Dispossessed', 'Duel', 'Foul Committed', 'Foul Won', 'Shot', 'Block', 'Goal Keeper', 'Injury Stoppage', 'Referee Ball-Drop', 'Interception', 'Miscontrol', 'Dribbled Past', 'Dribble', 'Substitution', 'Half End', 'Tactical Shift', 'Shield']
[35, 18, 30, 42, 43, 17, 9, 2, 3, 4, 22, 21, 16, 6, 23, 40, 41, 10, 38, 39, 14, 19, 34, 36, 28]

In [153]:
data=data.assign(type=lambda x:x['type'].apply(lambda d:d['name']))
data['type']

0          Starting XI
1          Starting XI
2           Half Start
3           Half Start
4                 Pass
             ...
3675    Foul Committed
3676          Foul Won
3677              Pass
3678          Half End
3679          Half End
Name: type, Length: 3680, dtype: str

In [154]:
pd.set_option('display.max_colwidth',None)
data['pass'].dropna().head(5)

4         {'recipient': {'id': 3043, 'name': 'Christian Dannemann Eriksen'}, 'length': 3.9446166, 'angle': -2.1025205, 'height': {'id': 1, 'name': 'Ground Pass'}, 'end_location': [58.0, 36.6], 'type': {'id': 65, 'name': 'Kick Off'}, 'body_part': {'id': 40, 'name': 'Right Foot'}}
7                                                          {'recipient': {'id': 17042, 'name': 'Andreas Skov Olsen'}, 'length': 19.36001, 'angle': 0.64246804, 'height': {'id': 1, 'name': 'Ground Pass'}, 'end_location': [74.8, 52.3], 'body_part': {'id': 40, 'name': 'Right Foot'}}
11                                                    {'recipient': {'id': 16190, 'name': 'Rasmus Nissen Kristensen'}, 'length': 21.972939, 'angle': 1.1437922, 'height': {'id': 1, 'name': 'Ground Pass'}, 'end_location': [86.5, 74.9], 'body_part': {'id': 38, 'name': 'Left Foot'}}
14    {'recipient': {'id': 6302, 'name': 'Kasper Dolberg'}, 'length': 38.910152, 'angle': -1.095655, 'height': {'id': 3, 'name': 'High Pass'}, 'end_location': [104.3, 40.3], 'cross': True, 'outcome': {'id': 9, 'name': 'Incomplete'}, 'body_part': {'id': 40, 'name': 'Right Foot'}}
17                  {'length': 42.19218, 'angle': 1.1378919, 'height': {'id': 3, 'name': 'High Pass'}, 'end_location': [118.0, 55.5], 'cross': True, 'body_part': {'id': 40, 'name': 'Right Foot'}, 'type': {'id': 66, 'name': 'Recovery'}, 'outcome': {'id': 9, 'name': 'Incomplete'}}
Name: pass, dtype: object

In [155]:
data[data['type']=='Pass'].shape

(1063, 36)

In [156]:
data['pass'].dropna().shape

(1063,)

In [157]:
data[data['type']=='Pass']['pass'].info()

<class 'pandas.Series'>
Index: 1063 entries, 4 to 3677
Series name: pass
Non-Null Count  Dtype
--------------  -----
1063 non-null   object
dtypes: object(1)
memory usage: 16.6+ KB

In [158]:
data[~(data['type']=='Pass')]['pass'].info()

<class 'pandas.Series'>
Index: 2617 entries, 0 to 3679
Series name: pass
Non-Null Count  Dtype
--------------  -----
0 non-null      object
dtypes: object(1)
memory usage: 40.9+ KB

In [159]:
data['shot'].dropna().head()

71                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {'statsbomb_xg': 0.023819994, 'end_location': [101.1, 47.5], 'key_pass_id': '2723ae5e-8801-436d-8c48-4e896ef63489', 'type': {'id': 87, 'name': 'Open Play'}, 'outcome': {'id': 96, 'name': 'Blocked'}, 'technique': {'id': 93, 'name': 'Normal'}, 'body_part': {'id': 40, 'name': 'Right Foot'}, 'freeze_frame': [{'location': [96.6, 52.5], 'player': {'id': 5527, 'name': 'Thomas Delaney'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [117.3, 39.6], 'player': {'id': 3815, 'name': 'Kasper Schmeichel'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [79.4, 40.2], 'player': {'id': 44955, 'name': 'Aïssa Bilal Laïdouni'}, 'position': {'id': 11, 'name': 'Left Defensive Midfield'}, 'teammate': True}, {'location': [92.4, 50.4], 'player': {'id': 3570, 'name': 'Pierre-Emile Højbjerg'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [87.4, 32.4], 'player': {'id': 17042, 'name': 'Andreas Skov Olsen'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': False}, {'location': [98.3, 56.3], 'player': {'id': 16554, 'name': 'Joakim Mæhle'}, 'position': {'id': 8, 'name': 'Left Wing Back'}, 'teammate': False}, {'location': [101.3, 47.8], 'player': {'id': 3959, 'name': 'Andreas Christensen'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [91.7, 54.0], 'player': {'id': 5534, 'name': 'Simon Thorup Kjær'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': False}, {'location': [99.0, 40.5], 'player': {'id': 8247, 'name': 'Joachim Andersen'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [101.8, 33.4], 'player': {'id': 16190, 'name': 'Rasmus Nissen Kristensen'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': False}, {'location': [100.8, 54.7], 'player': {'id': 9236, 'name': 'Mohamed Dräger'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': True}, {'location': [104.6, 51.2], 'player': {'id': 35592, 'name': 'Anis Ben Slimane'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': True}, {'location': [96.9, 43.0], 'player': {'id': 16352, 'name': 'Issam Jebali'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}]}
182                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {'statsbomb_xg': 0.014059674000000001, 'end_location': [114.6, 53.3], 'body_part': {'id': 38, 'name': 'Left Foot'}, 'type': {'id': 87, 'name': 'Open Play'}, 'outcome': {'id': 96, 'name': 'Blocked'}, 'technique': {'id': 93, 'name': 'Normal'}, 'freeze_frame': [{'location': [107.0, 49.4], 'player': {'id': 9236, 'name': 'Mohamed Dräger'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': True}, {'location': [114.3, 57.9], 'player': {'id': 35592, 'name': 'Anis Ben Slimane'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': True}, {'location': [112.1, 42.0], 'player': {'id': 23910, 'name': 'Youssef Msakni'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': True}, {'location': [113.7, 38.2], 'player': {'id': 30681, 'name': 'Ali Abdi'}, 'position': {'id': 8, 'name': 'Left Wing Back'}, 'teammate': True}, {'location': [110.6, 59.7], 'player': {'id': 16554, 'name': 'Joakim Mæhle'}, 'position': {'id': 8, 'name': 'Left Wing Back'}, 'teammate': False}, {'location': [108.1, 51.7], 'player': {'id': 3043, 'name': 'Christian Dannemann Eriksen'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [113.9, 51.0], 'player': {'id': 5527, 'name': 'Thomas Delaney'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [114.7, 52.7], 'player': {'id': 3959, 'name': 'Andreas Christensen'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [109.1, 45.1], 'player': {'id': 3570, 'name': 'Pierre-Emile Højbjerg'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [101.1, 32.4], 'player': {'id': 17042, 'name': 'Andreas Skov Olsen'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': False}, {'location': [113.9, 43.2], 'player': {'id': 5534, 'name': 'Simon Thorup Kjær'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': False}, {'location': [113.3, 41.5], 'player': {'id': 16190, 'name': 'Rasmus Nissen Kristensen'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': False}, {'location': [114.7, 37.5], 'player': {'id': 8247, 'name': 'Joachim Andersen'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [118.9, 43.8], 'player': {'id': 3815, 'name': 'Kasper Schmeichel'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}]}
505                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {'statsbomb_xg': 0.033114884000000004, 'end_location': [98.1, 43.9], 'key_pass_id': '134144c1-38b8-4fe4-ad90-21ea23f115d3', 'technique': {'id': 93, 'name': 'Normal'}, 'body_part': {'id': 40, 'name': 'Right Foot'}, 'type': {'id': 87, 'name': 'Open Play'}, 'outcome': {'id': 96, 'name': 'Blocked'}, 'freeze_frame': [{'location': [102.1, 41.4], 'player': {'id': 16352, 'name': 'Issam Jebali'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}, {'location': [89.9, 17.9], 'player': {'id': 30681, 'name': 'Ali Abdi'}, 'position': {'id': 8, 'name': 'Left Wing Back'}, 'teammate': True}, {'location': [96.9, 25.4], 'player': {'id': 23910, 'name': 'Youssef Msakni'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': True}, {'location': [104.0, 35.9], 'player': {'id': 3767, 'name': 'Ellyes Joris Skhiri'}, 'position': {'id': 9, 'name': 'Right Defensive Midfield'}, 'teammate': True}, {'location': [101.9, 26.2], 'player': {'id': 35592, 'name': 'Anis Ben Slimane'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': True}, {'location': [94.3, 42.9], 'player': {'id': 3043, 'name': 'Christian Dannemann Eriksen'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [98.8, 44.0], 'player': {'id': 3959, 'name': 'Andreas Christensen'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [96.0, 33.7], 'player': {'id': 5527, 'name': 'Thomas Delaney'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [103.4, 47.0], 'player': {'id': 16554, 'name': 'Joakim Mæhle'}, 'position': {'id': 8, 'name': 'Left Wing Back'}, 'teammate': False}, {'location': [91.9, 22.6], 'player': {'id': 3570, 'name': 'Pierre-Emile Højbjerg'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [103.0, 39.9], 'player': {'id': 5534, 'name': 'Simon Thorup Kjær'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': False}, {'location': [90.1, 16.5], 'player': {'id': 17042, 'name': 'Andreas Skov Olsen'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': False}, {'location': [104.7, 34.8], 'player': {'id': 8247, 'name': 'Joachim Andersen'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [103.7, 28.0], 'player': {'id': 16190, 'name': 'Rasmus Nissen Kristensen'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': False}, {'location': [115.7, 39.8], 'player': {'id': 3815, 'name': 'Kasper Schmeichel'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}]}
510                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {'statsbomb_xg': 0.04366076, 'end_location': [120.0, 43.4, 3.8], 'key_pass_id': 'cf306b75-1e23-40f4-a54e-369dc2ca5480', 'technique': {'id': 93, 'name': 'Normal'}, 'body_part': {'id': 37, 'name': 'Head'}, 'type': {'id': 87, 'name': 'Open Play'}, 'outcome': {'id': 98, 'name': 'Off T'}, 'freeze_frame': [{'location': [112.5, 39.1], 'player': {'id': 6302, 'name': 'Kasper Dolberg'}, 'position': {'id': 24, 'name': 'Left Center Forward'}, 'teammate': False}, {'location': [118.9, 43.6], 'player': {'id': 16190, 'name': 'Rasmus Nissen Kristensen'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': False}, {'location': [118.6, 39.0], 'player': {'id': 3815, 'name': 'Kasper Schmeichel'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [107.6, 38.1], 'player': {'id': 16554, 'name': 'Joakim Mæhle'}, 'position': {'id': 8, 'name': 'Left Wing Back'}, 'teammate': False}, {'location': [105.9, 32.2], 'player': {'id': 3043, 'name': 'Christian Dannemann Eriksen'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [115.2, 39.5], 'player': {'id': 3959, 'name': 'Andreas Christensen'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [112.9, 37.9], 'player': {'id': 5527, 'name': 'Thomas Delaney'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [114.5, 35.6], 'player': {'id': 5534, 'name': 'Simon Thorup Kjær'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': False}, {'location': [114.9, 33.0], 'player': {'id': 8247, 'name': 'Joachim Andersen'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [115.2, 31.5], 'player': {'id': 3570, 'name': 'Pierre-Emile Højbjerg'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [100.7, 32.8], 'player': {'id': 3767, 'name': 'Ellyes Joris Skhiri'}, 'position': {'id': 9, 'name': 'Right Defensive Midfield'}, 'teammate': True}, {'location': [110.1, 41.4], 'player': {'id': 5655, 'name': 'Dylan Daniel Mahmoud Bronn'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': True}, {'location': [111.2, 38.2], 'player': {'id': 32450, 'name': 'Montassar Omar Talbi'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': True}, {'location': [111.3, 35.5], 'player': {'id': 5651, 'name': 'Yassine Meriah'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': True}, {'location': [114.0, 37.4], 'player': {'id': 16352, 'name': 'Issam Jebali'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}]}
848    {'statsbomb_xg': 0.12403256400000001, 'end_location': [116.0, 33.8], 'key_pass_id': 'b0d736a6-afb5-433d-a748-04e26ccb96ab', 'first_time': True, 'technique': {'id': 95, 'name': 'Volley'}, 'body_part': {'id': 40, 'name': 'Right Foot'}, 'type': {'id': 87, 'name': 'Open Play'}, 'outcome': {'id': 96, 'name': 'Blocked'}, 'freeze_frame': [{'location': [111.1, 14.6], 'player': {'id': 3043, 'name': 'Christian Dannemann Eriksen'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': True}, {'location': [111.7, 34.9], 'player': {'id': 3767, 'name': 'Ellyes Joris Skhiri'}, 'position': {'id': 9, 'name': 'Right Defensive Midfield'}, 'teammate': False}, {'location': [110.2, 32.4], 'player': {'id': 16352, 'name': 'Issam Jebali'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': False}, {'location': [113.3, 24.6], 'player': {'id': 44955, 'name': 'Aïssa Bilal Laïdouni'}, 'position': {'id': 11, 'name': 'Left Defensive Midfield'}, 'teammate': False}, {'location': [101.1, 40.8], 'player': {'id': 23910, 'name': 'Youssef Msakni'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': False}, {'location': [112.4, 17.8], 'player': {'id': 9236, 'name': 'Mohamed Dräger'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': False}, {'location': [105.6, 27.6], 'player': {'id': 35592, 'name': 'Anis Ben Slimane'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': False}, {'location': [118.2, 36.9], 'player': {'id': 105943, 'name': 'Aymen Dahmen'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [111.9, 52.8], 'player': {'id': 5527, 'name': 'Thomas Delaney'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': True}, {'location': [113.7, 44.2], 'player': {'id': 5534, 'name': 'Simon Thorup Kjær'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': True}, {'location': [110.7, 34.2], 'player': {'id': 3959, 'name': 'Andreas Christensen'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': True}, {'location': [97.1, 52.5], 'player': {'id': 16190, 'name': 'Rasmus Nissen Kristensen'}, 'position': {'id': 7, 'name': 'Right Wing Back'}, 'teammate': True}, {'location': [104.1, 33.7], 'player': {'id': 8247, 'name': 'Joachim Andersen'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': True}, {'location': [99.7, 29.3], 'player': {'id': 17042, 'name': 'Andreas Skov Olsen'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': True}, {'location': [112.4, 47.5], 'player': {'id': 30681, 'name': 'Ali Abdi'}, 'position': {'id': 8, 'name': 'Left Wing Back'}, 'teammate': False}, {'location': [114.3, 43.2], 'player': {'id': 5655, 'name': 'Dylan Daniel Mahmoud Bronn'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [114.7, 39.0], 'player': {'id': 5651, 'name': 'Yassine Meriah'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': False}, {'location': [115.4, 34.3], 'player': {'id': 32450, 'name': 'Montassar Omar Talbi'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}]}
Name: shot, dtype: object

In [160]:
data[data['type']=='Shot'].shape[0]

24

In [161]:
data[~(data['type']=='Shot')]['shot'].info()

<class 'pandas.Series'>
Index: 3656 entries, 0 to 3679
Series name: shot
Non-Null Count  Dtype
--------------  -----
0 non-null      object
dtypes: object(1)
memory usage: 57.1+ KB

In [162]:
data[data['type']=='Shot']['shot'].info()

<class 'pandas.Series'>
Index: 24 entries, 71 to 3666
Series name: shot
Non-Null Count  Dtype
--------------  -----
24 non-null     object
dtypes: object(1)
memory usage: 384.0+ bytes

In [163]:
data['duel'].dropna().head(10)

33            {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 14, 'name': 'Lost Out'}}
45                                                  {'type': {'id': 10, 'name': 'Aerial Lost'}}
179                 {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 4, 'name': 'Won'}}
269    {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 16, 'name': 'Success In Play'}}
290    {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 16, 'name': 'Success In Play'}}
387                                                 {'type': {'id': 10, 'name': 'Aerial Lost'}}
413                                                 {'type': {'id': 10, 'name': 'Aerial Lost'}}
435    {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 16, 'name': 'Success In Play'}}
494           {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 14, 'name': 'Lost Out'}}
538                                                 {'type': {'id': 10, 'name': 'Aerial Lost'}}
Name: duel, dtype: object

In [164]:
unique_dual = []
for i in data['duel'].dropna().to_list():
    duel_type = i['type']['name']
    outcome = i.get('outcome', {}).get('name')
    value = (duel_type, outcome)
    if value not in unique_dual:
        unique_dual.append(value)
print(unique_dual)

[('Tackle', 'Lost Out'), ('Aerial Lost', None), ('Tackle', 'Won'), ('Tackle', 'Success In Play'), ('Tackle', 'Lost In Play'), ('Tackle', 'Success Out')]

In [165]:
data['duel'].dropna().to_list()

[{'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 4, 'name': 'Won'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 4, 'name': 'Won'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 4, 'name': 'Won'}},
 {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 4, 'name': 'Won'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'outcome': {'id': 4, 'name': 'Won'}, 'type': {'id': 11, 'name': 'Tackle'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 4, 'name': 'Won'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'}, 'outcome': {'id': 4, 'name': 'Won'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'outcome': {'id': 13, 'name': 'Lost In Play'},
  'type': {'id': 11, 'name': 'Tackle'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'outcome': {'id': 4, 'name': 'Won'}, 'type': {'id': 11, 'name': 'Tackle'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 17, 'name': 'Success Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'outcome': {'id': 16, 'name': 'Success In Play'},
  'type': {'id': 11, 'name': 'Tackle'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}},
 {'type': {'id': 11, 'name': 'Tackle'},
  'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'type': {'id': 10, 'name': 'Aerial Lost'}}]

In [166]:
data['type'] = data.apply(
    lambda row: row['type']
    if pd.isna(row['duel'])
    else row['duel']['type']['name'],
    axis=1
)
data['type'].unique()

<StringArray>
[      'Starting XI',        'Half Start',              'Pass',
     'Ball Receipt*',             'Carry',          'Pressure',
         'Clearance',     'Ball Recovery',      'Dispossessed',
            'Tackle',       'Aerial Lost',    'Foul Committed',
          'Foul Won',              'Shot',             'Block',
       'Goal Keeper',   'Injury Stoppage', 'Referee Ball-Drop',
      'Interception',        'Miscontrol',     'Dribbled Past',
           'Dribble',      'Substitution',          'Half End',
    'Tactical Shift',            'Shield']
Length: 26, dtype: str

In [167]:
data['ball_recovery'].dropna().to_list()

[{'recovery_failure': True},
 {'recovery_failure': True},
 {'recovery_failure': True},
 {'recovery_failure': True},
 {'recovery_failure': True}]

In [168]:
data['interception'].dropna().to_list()

[{'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'outcome': {'id': 4, 'name': 'Won'}},
 {'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'outcome': {'id': 4, 'name': 'Won'}},
 {'outcome': {'id': 4, 'name': 'Won'}},
 {'outcome': {'id': 4, 'name': 'Won'}},
 {'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'outcome': {'id': 4, 'name': 'Won'}},
 {'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'outcome': {'id': 14, 'name': 'Lost Out'}},
 {'outcome': {'id': 4, 'name': 'Won'}},
 {'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'outcome': {'id': 13, 'name': 'Lost In Play'}},
 {'outcome': {'id': 4, 'name': 'Won'}},
 {'outcome': {'id': 16, 'name': 'Success In Play'}},
 {'outcome': {'id': 14, 'name': 'Lost Out'}}]

In [169]:
unique_interception=[]
for i in data['interception'].dropna().to_list():
    if i['outcome']['name'] not in unique_interception:
        unique_interception.append(i['outcome']['name'])
print(unique_interception)

['Lost Out', 'Lost In Play', 'Won', 'Success In Play']

In [170]:
data['dribble'].dropna().to_list()

[{'outcome': {'id': 9, 'name': 'Incomplete'}, 'overrun': True},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'nutmeg': True, 'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'nutmeg': True, 'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'overrun': True, 'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 8, 'name': 'Complete'}},
 {'outcome': {'id': 9, 'name': 'Incomplete'}}]

In [171]:
unique_dribble=[]
for i in data['dribble'].dropna().to_list():
    if i['outcome']['name'] not in unique_dribble:
        unique_dribble.append(i['outcome']['name'])
print(unique_dribble)

['Incomplete', 'Complete']

In [172]:
data['clearance'].dropna().to_list()

[{'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'left_foot': True, 'body_part': {'id': 38, 'name': 'Left Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'left_foot': True, 'body_part': {'id': 38, 'name': 'Left Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'left_foot': True, 'body_part': {'id': 38, 'name': 'Left Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'left_foot': True, 'body_part': {'id': 38, 'name': 'Left Foot'}},
 {'aerial_won': True, 'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'left_foot': True, 'body_part': {'id': 38, 'name': 'Left Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'aerial_won': True, 'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'other': True, 'body_part': {'id': 70, 'name': 'Other'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'left_foot': True, 'body_part': {'id': 38, 'name': 'Left Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'left_foot': True, 'body_part': {'id': 38, 'name': 'Left Foot'}},
 {'aerial_won': True, 'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'aerial_won': True, 'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'other': True, 'body_part': {'id': 70, 'name': 'Other'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'right_foot': True, 'body_part': {'id': 40, 'name': 'Right Foot'}},
 {'head': True, 'body_part': {'id': 37, 'name': 'Head'}},
 {'aerial_won': True, 'head': True, 'body_part': {'id': 37, 'name': 'Head'}}]

In [173]:
data['foul_committed'].dropna().to_list()

[{'advantage': True},
 {'advantage': True},
 {'card': {'id': 7, 'name': 'Yellow Card'}},
 {'advantage': True},
 {'advantage': True},
 {'offensive': True, 'type': {'id': 24, 'name': 'Handball'}},
 {'card': {'id': 7, 'name': 'Yellow Card'}},
 {'card': {'id': 7, 'name': 'Yellow Card'}}]

In [174]:
data[data['type']=='Dispossessed'].shape[0]

25

In [175]:
data['related_events'].head(10)

0                                                                                                                   NaN
1                                                                                                                   NaN
2                                                                                [6949d93f-9fca-434a-8d66-ef2dccc8dcd2]
3                                                                                [8e0db96c-ed4c-410f-95f2-650f0de594bb]
4                                                                                [86eb15d6-28af-43b9-952d-c8fa4d56c6e4]
5                                                                                [9266e43f-c76a-413b-8c25-9b61c1aefe49]
6                                          [e59abeb7-b8a4-49f8-9580-93b06348e5de, 86eb15d6-28af-43b9-952d-c8fa4d56c6e4]
7                                                                                [26bfda4b-25b7-4ac3-ae73-d41a11c49a4a]
8                                                                                [e59abeb7-b8a4-49f8-9580-93b06348e5de]
9    [5500d603-002a-49c5-8b49-3a7dfa25f294, 107c8c1a-e892-40bf-b562-7c43a64d2c5f, 26bfda4b-25b7-4ac3-ae73-d41a11c49a4a]
Name: related_events, dtype: object

In [176]:
columns=['team','minute','second','type','period','play_pattern']
for column in data.columns:
    if column not in columns:
        data=data.drop(columns=column)
data.head()

,period,minute,second,type,play_pattern,team
0,1,0,0,Starting XI,"{'id': 1, 'name': 'Regular Play'}","{'id': 776, 'name': 'Denmark'}"
1,1,0,0,Starting XI,"{'id': 1, 'name': 'Regular Play'}","{'id': 777, 'name': 'Tunisia'}"
2,1,0,0,Half Start,"{'id': 1, 'name': 'Regular Play'}","{'id': 776, 'name': 'Denmark'}"
3,1,0,0,Half Start,"{'id': 1, 'name': 'Regular Play'}","{'id': 777, 'name': 'Tunisia'}"
4,1,0,0,Pass,"{'id': 9, 'name': 'From Kick Off'}","{'id': 776, 'name': 'Denmark'}"

In [177]:
data=data.assign(play_pattern=lambda x:x['play_pattern'].apply(lambda d:d['name']),team=lambda x:x['team'].apply(lambda d:d['name']),match_id=3857254)
data.head()

   period  minute  second         type   play_pattern     team  match_id
0       1       0       0  Starting XI   Regular Play  Denmark   3857254
1       1       0       0  Starting XI   Regular Play  Tunisia   3857254
2       1       0       0   Half Start   Regular Play  Denmark   3857254
3       1       0       0   Half Start   Regular Play  Tunisia   3857254
4       1       0       0         Pass  From Kick Off  Denmark   3857254

In [178]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3680 entries, 0 to 3679
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   period        3680 non-null   int64
 1   minute        3680 non-null   int64
 2   second        3680 non-null   int64
 3   type          3680 non-null   str
 4   play_pattern  3680 non-null   str
 5   team          3680 non-null   str
 6   match_id      3680 non-null   int64
dtypes: int64(4), str(3)
memory usage: 201.4 KB

In [179]:
data['match_time']=(pd.to_timedelta(data['minute'],unit='m') + pd.to_timedelta(data['second'],unit='s'))
data.head()

,period,minute,second,type,play_pattern,team,match_id,match_time
0,1,0,0,Starting XI,Regular Play,Denmark,3857254,0 days
1,1,0,0,Starting XI,Regular Play,Tunisia,3857254,0 days
2,1,0,0,Half Start,Regular Play,Denmark,3857254,0 days
3,1,0,0,Half Start,Regular Play,Tunisia,3857254,0 days
4,1,0,0,Pass,From Kick Off,Denmark,3857254,0 days

In [180]:
column_not_drop=['Pass','Clearance','Ball Recovery','Dispossessed','Foul Committed','Shot','Interception','Dribble','Tackle','Foul Won','Dribbled Past']
data_clean=data[data['type'].isin(column_not_drop)]
data_clean.head()

,period,minute,second,type,play_pattern,team,match_id,match_time
4,1,0,0,Pass,From Kick Off,Denmark,3857254,0 days 00:00:00
7,1,0,1,Pass,From Kick Off,Denmark,3857254,0 days 00:00:01
11,1,0,3,Pass,From Kick Off,Denmark,3857254,0 days 00:00:03
14,1,0,5,Pass,From Kick Off,Denmark,3857254,0 days 00:00:05
16,1,0,7,Clearance,From Kick Off,Tunisia,3857254,0 days 00:00:07

In [181]:
data_dummy=pd.get_dummies(data_clean,columns=['type'],dtype=int)
data_dummy.head()

,period,minute,second,play_pattern,team,match_id,match_time,type_Ball Recovery,type_Clearance,type_Dispossessed,type_Dribble,type_Dribbled Past,type_Foul Committed,type_Foul Won,type_Interception,type_Pass,type_Shot,type_Tackle
4,1,0,0,From Kick Off,Denmark,3857254,0 days 00:00:00,0,0,0,0,0,0,0,0,1,0,0
7,1,0,1,From Kick Off,Denmark,3857254,0 days 00:00:01,0,0,0,0,0,0,0,0,1,0,0
11,1,0,3,From Kick Off,Denmark,3857254,0 days 00:00:03,0,0,0,0,0,0,0,0,1,0,0
14,1,0,5,From Kick Off,Denmark,3857254,0 days 00:00:05,0,0,0,0,0,0,0,0,1,0,0
16,1,0,7,From Kick Off,Tunisia,3857254,0 days 00:00:07,0,1,0,0,0,0,0,0,0,0,0

In [182]:
data_dummy.info()

<class 'pandas.DataFrame'>
Index: 1412 entries, 4 to 3677
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   period               1412 non-null   int64
 1   minute               1412 non-null   int64
 2   second               1412 non-null   int64
 3   play_pattern         1412 non-null   str
 4   team                 1412 non-null   str
 5   match_id             1412 non-null   int64
 6   match_time           1412 non-null   timedelta64[s]
 7   type_Ball Recovery   1412 non-null   int64
 8   type_Clearance       1412 non-null   int64
 9   type_Dispossessed    1412 non-null   int64
 10  type_Dribble         1412 non-null   int64
 11  type_Dribbled Past   1412 non-null   int64
 12  type_Foul Committed  1412 non-null   int64
 13  type_Foul Won        1412 non-null   int64
 14  type_Interception    1412 non-null   int64
 15  type_Pass            1412 non-null   int64
 16  type_Shot            1412 non-null   int64
 17  type_Tackle          1412 non-null   int64
dtypes: int64(15), str(2), timedelta64[s](1)
memory usage: 209.6 KB

In [183]:
data_dummy[['type_Foul Committed','type_Foul Won']].value_counts()

type_Foul Committed  type_Foul Won
0                    0                1367
1                    0                  23
0                    1                  22
Name: count, dtype: int64

In [184]:
data_dummy[['type_Dribble','type_Dribbled Past']].value_counts()

type_Dribble  type_Dribbled Past
0             0                     1368
1             0                       30
0             1                       14
Name: count, dtype: int64

In [185]:
data_dummy[((data_dummy['type_Foul Won']==1)|(data_dummy['type_Foul Committed']==1))][['type_Foul Won','type_Foul Committed']]

      type_Foul Won  type_Foul Committed
66                0                    1
67                1                    0
156               0                    1
157               1                    0
366               0                    1
367               1                    0
645               0                    1
646               1                    0
834               0                    1
835               1                    0
911               0                    1
912               1                    0
1173              0                    1
1174              1                    0
1243              0                    1
1244              1                    0
1402              0                    1
1403              1                    0
1679              0                    1
1680              1                    0
1695              0                    1
1696              1                    0
1709              0                    1
1710              1                    0
1815              0                    1
1816              1                    0
1969              0                    1
1970              1                    0
2438              0                    1
2439              1                    0
2774              0                    1
3156              0                    1
3157              1                    0
3170              0                    1
3171              1                    0
3352              0                    1
3353              1                    0
3430              0                    1
3431              1                    0
3605              0                    1
3606              1                    0
3669              0                    1
3670              1                    0
3675              0                    1
3676              1                    0

In [186]:
data_dummy[((data_dummy['type_Dribble']==1)|(data_dummy['type_Dribbled Past']==1))][['type_Dribble','type_Dribbled Past']]

      type_Dribble  type_Dribbled Past
190              0                   1
191              1                   0
630              1                   0
635              1                   0
673              0                   1
674              1                   0
720              1                   0
820              0                   1
821              1                   0
829              1                   0
1247             0                   1
1248             1                   0
1254             1                   0
1428             1                   0
1686             1                   0
1831             0                   1
1832             1                   0
1966             1                   0
1987             1                   0
1992             1                   0
2002             1                   0
2123             0                   1
2124             1                   0
2268             1                   0
2856             0                   1
2857             1                   0
2890             0                   1
2891             1                   0
2896             0                   1
2897             1                   0
2900             1                   0
2919             0                   1
2920             1                   0
3390             0                   1
3391             1                   0
3413             0                   1
3414             1                   0
3442             1                   0
3488             1                   0
3498             0                   1
3499             1                   0
3591             0                   1
3592             1                   0
3623             1                   0

In [187]:
data_dummy=data_dummy.drop(columns=['type_Dribbled Past','type_Foul Won'])
data_dummy.columns

Index(['period', 'minute', 'second', 'play_pattern', 'team', 'match_id',
       'match_time', 'type_Ball Recovery', 'type_Clearance',
       'type_Dispossessed', 'type_Dribble', 'type_Foul Committed',
       'type_Interception', 'type_Pass', 'type_Shot', 'type_Tackle'],
      dtype='str')

In [188]:
column_to_compare_2022=['type_Pass','type_Shot','type_Foul Committed','type_Interception','type_Dribble','type_Clearance','type_Ball Recovery','type_Dispossessed','type_Tackle']
for column in data_dummy.columns:
    if column in column_to_compare_2022:
        print(data_dummy[column].value_counts())

type_Ball Recovery
0    1317
1      95
Name: count, dtype: int64
type_Clearance
0    1359
1      53
Name: count, dtype: int64
type_Dispossessed
0    1387
1      25
Name: count, dtype: int64
type_Dribble
0    1382
1      30
Name: count, dtype: int64
type_Foul Committed
0    1389
1      23
Name: count, dtype: int64
type_Interception
0    1390
1      22
Name: count, dtype: int64
type_Pass
1    1063
0     349
Name: count, dtype: int64
type_Shot
0    1388
1      24
Name: count, dtype: int64
type_Tackle
0    1371
1      41
Name: count, dtype: int64

In [189]:
data_dummy=data_dummy.rename(columns={'type_Pass':'pass','type_Shot':'shot','type_Foul Committed':'foul','type_Interception':'interception','type_Dribble':'dribble','type_Clearance':'clearance','type_Ball Recovery':'ball_recovery','type_Dispossessed':'dispossessed','type_Tackle':'tackle'})
data_dummy.columns

Index(['period', 'minute', 'second', 'play_pattern', 'team', 'match_id',
       'match_time', 'ball_recovery', 'clearance', 'dispossessed', 'dribble',
       'foul', 'interception', 'pass', 'shot', 'tackle'],
      dtype='str')

In [190]:
data_dummy.head()

,period,minute,second,play_pattern,team,match_id,match_time,ball_recovery,clearance,dispossessed,dribble,foul,interception,pass,shot,tackle
4,1,0,0,From Kick Off,Denmark,3857254,0 days 00:00:00,0,0,0,0,0,0,1,0,0
7,1,0,1,From Kick Off,Denmark,3857254,0 days 00:00:01,0,0,0,0,0,0,1,0,0
11,1,0,3,From Kick Off,Denmark,3857254,0 days 00:00:03,0,0,0,0,0,0,1,0,0
14,1,0,5,From Kick Off,Denmark,3857254,0 days 00:00:05,0,0,0,0,0,0,1,0,0
16,1,0,7,From Kick Off,Tunisia,3857254,0 days 00:00:07,0,1,0,0,0,0,0,0,0

In [191]:
data_dummy['match_time']

4      0 days 00:00:00
7      0 days 00:00:01
11     0 days 00:00:03
14     0 days 00:00:05
16     0 days 00:00:07
             ...
3670   0 days 01:36:38
3671   0 days 01:36:57
3675   0 days 01:37:02
3676   0 days 01:37:02
3677   0 days 01:37:33
Name: match_time, Length: 1412, dtype: timedelta64[s]

In [192]:
data_12_22,data_22_32,data_57_67,data_67_77=time_extractor(data_dummy,2022)
data_12_22

,period,minute,second,play_pattern,team,match_id,match_time,ball_recovery,clearance,dispossessed,dribble,foul,interception,pass,shot,tackle
512,1,12,14,From Goal Kick,Denmark,3857254,0 days 00:12:14,0,0,0,0,0,0,1,0,0
513,1,12,18,From Goal Kick,Tunisia,3857254,0 days 00:12:18,0,1,0,0,0,0,0,0,0
514,1,12,22,Regular Play,Tunisia,3857254,0 days 00:12:22,1,0,0,0,0,0,0,0,0
516,1,12,26,Regular Play,Tunisia,3857254,0 days 00:12:26,0,0,0,0,0,0,1,0,0
519,1,12,30,Regular Play,Tunisia,3857254,0 days 00:12:30,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,1,20,28,From Corner,Denmark,3857254,0 days 00:20:28,0,0,0,0,0,0,0,0,0
836,1,21,17,From Free Kick,Denmark,3857254,0 days 00:21:17,0,0,0,0,0,0,1,0,0
837,1,21,19,From Free Kick,Tunisia,3857254,0 days 00:21:19,0,1,0,0,0,0,0,0,0
838,1,21,56,From Corner,Denmark,3857254,0 days 00:21:56,0,0,0,0,0,0,1,0,0
841,1,21,59,From Corner,Denmark,3857254,0 days 00:21:59,0,0,0,0,0,0,1,0,0

In [193]:
input_folder = Path(
    r"C:\Users\dawit\PycharmProjects\hydration break\data\2022"
)
output_folder = Path(
    r"C:\Users\dawit\PycharmProjects\hydration break\data\2022_cleaned"
)
output_folder.mkdir(parents=True, exist_ok=True)
for file in input_folder.glob("*.json"):
    data = pd.read_json(file)
    match_id = int(file.stem)
    # Step 1: Extract event name from type
    data = data.assign(
        type=lambda x: x['type'].apply(lambda d: d['name'])
    )
    # Step 2: Replace Duel with its specific subtype
    data['type'] = data.apply(
        lambda row: row['type']
        if pd.isna(row['duel'])
        else row['duel']['type']['name'],
        axis=1
    )
    # Step 3: Keep required columns
    columns = [
        'team',
        'minute',
        'second',
        'type',
        'period',
        'play_pattern'
    ]
    for column in data.columns:
        if column not in columns:
            data = data.drop(columns=column, errors='ignore')
    # Step 4: Extract names and add match ID
    data = data.assign(
        play_pattern=lambda x: x['play_pattern'].apply(lambda d: d['name']),
        team=lambda x: x['team'].apply(lambda d: d['name']),
        match_id=match_id
    )
    # Step 5: Create match_time
    data['match_time'] = (
        pd.to_timedelta(data['minute'], unit='m')
        + pd.to_timedelta(data['second'], unit='s')
    )
    # Step 6: Keep the nine common event types
    column_not_drop = [
        'Pass',
        'Clearance',
        'Ball Recovery',
        'Dispossessed',
        'Foul Committed',
        'Shot',
        'Interception',
        'Dribble',
        'Tackle'
    ]
    data_clean = data[
        data['type'].isin(column_not_drop)
    ]
    # Step 7: One-hot encode event types
    data_dummy = pd.get_dummies(
        data_clean,
        columns=['type'],
        dtype=int
    )
    # Step 8: Rename event columns
    data_dummy = data_dummy.rename(
        columns={
            'type_Pass': 'pass',
            'type_Shot': 'shot',
            'type_Foul Committed': 'foul',
            'type_Interception': 'interception',
            'type_Dribble': 'dribble',
            'type_Clearance': 'clearance',
            'type_Ball Recovery': 'ball_recovery',
            'type_Dispossessed': 'dispossessed',
            'type_Tackle': 'tackle'
        }
    )
    # Step 9: Extract the four 2022 time windows
    data_12_22, data_22_32, data_57_67, data_67_77 = (
        time_extractor(data_dummy, 2022)
    )
    # Save each window as CSV
    windows = {
        "12_22": data_12_22,
        "22_32": data_22_32,
        "57_67": data_57_67,
        "67_77": data_67_77
    }
    for window_name, window_data in windows.items():

        output_file = output_folder / (
            f"{match_id}_2022_{window_name}.csv"
        )
        # to_csv overwrites an existing file
        window_data.to_csv(
            output_file,
            index=False
        )
print("2022 cleaning and extraction complete.")

2022 cleaning and extraction complete.